package com.zopchat;

import android.os.Bundle; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import androidx.recyclerview.widget.*; import com.google.firebase.auth.FirebaseAuth; import com.google.firebase.firestore.*; import java.util.*;

public class ChatActivity extends AppCompatActivity{
    String chatId, otherUid, uid; FirebaseFirestore db; MessageAdapter adapter; EditText msgEt; ListenerRegistration msgListener,userListener;
    @Override protected void onCreate(Bundle b){super.onCreate(b); setContentView(R.layout.activity_chat); db=FirebaseFirestore.getInstance(); uid=FirebaseAuth.getInstance().getUid(); chatId=getIntent().getStringExtra("chatId"); otherUid=getIntent().getStringExtra("otherUid"); String name=getIntent().getStringExtra("name"), mobile=getIntent().getStringExtra("mobile");
        ((TextView)findViewById(R.id.nameTv)).setText(name==null||name.isEmpty()?mobile:name); ((TextView)findViewById(R.id.avatarTv)).setText(Utils.firstLetter(name)); findViewById(R.id.backBtn).setOnClickListener(v->finish()); msgEt=findViewById(R.id.messageEt); findViewById(R.id.sendBtn).setOnClickListener(v->send()); RecyclerView rv=findViewById(R.id.messageRecycler); LinearLayoutManager lm=new LinearLayoutManager(this); lm.setStackFromEnd(true); rv.setLayoutManager(lm); adapter=new MessageAdapter(uid); rv.setAdapter(adapter); listenUser(); listenMessages(rv); }
    void listenUser(){ userListener=db.collection("users").document(otherUid).addSnapshotListener((s,e)->{ if(s!=null&&s.exists()) ((TextView)findViewById(R.id.statusTv)).setText(Utils.lastSeenText(s.get("online"), s.getTimestamp("lastSeen"))); }); }
    void listenMessages(RecyclerView rv){ msgListener=db.collection("chats").document(chatId).collection("messages").orderBy("createdAt", Query.Direction.ASCENDING).limit(300).addSnapshotListener((sn,e)->{ if(sn==null)return; List<MessageRow> list=new ArrayList<>(); for(DocumentSnapshot d:sn){ MessageRow m=new MessageRow(); m.id=d.getId(); m.senderId=d.getString("senderId"); m.text=d.getString("text"); m.type=d.getString("type"); m.createdAt=d.getTimestamp("createdAt"); list.add(m); if(!uid.equals(m.senderId)){ Map<String,Object> seen=new HashMap<>(); seen.put("readBy."+uid,true); seen.put("readAt",FieldValue.serverTimestamp()); d.getReference().set(seen,SetOptions.merge()); }} adapter.setRows(list); rv.scrollToPosition(Math.max(0,list.size()-1)); }); }
    void send(){ String text=msgEt.getText().toString().trim(); if(text.isEmpty())return; msgEt.setText(""); Map<String,Object> m=new HashMap<>(); m.put("senderId",uid); m.put("text",text); m.put("type","text"); m.put("createdAt",FieldValue.serverTimestamp()); m.put("status","sent"); Map<String,Object> read=new HashMap<>(); read.put(uid,true); m.put("readBy",read); db.collection("chats").document(chatId).collection("messages").add(m); Map<String,Object> c=new HashMap<>(); c.put("lastMessage",text); c.put("lastMessageType","text"); c.put("lastMessageAt",FieldValue.serverTimestamp()); c.put("lastMessageSenderId",uid); c.put("updatedAt",FieldValue.serverTimestamp()); db.collection("chats").document(chatId).set(c,SetOptions.merge()); }
    @Override protected void onResume(){super.onResume();PresenceManager.setOnline(true);} @Override protected void onPause(){super.onPause();PresenceManager.setOnline(false);} @Override protected void onDestroy(){ if(msgListener!=null)msgListener.remove(); if(userListener!=null)userListener.remove(); super.onDestroy(); }
}
