package com.zopchat;

import android.content.*; import android.os.Bundle; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import androidx.recyclerview.widget.*;
import com.google.firebase.auth.FirebaseAuth; import com.google.firebase.firestore.*; import java.util.*;

public class MainActivity extends AppCompatActivity{
    FirebaseFirestore db; FirebaseAuth auth; ChatListAdapter adapter; EditText searchEt; ListenerRegistration chatListener; String uid;
    @Override protected void onCreate(Bundle b){super.onCreate(b); setContentView(R.layout.activity_main); db=FirebaseFirestore.getInstance(); auth=FirebaseAuth.getInstance(); uid=auth.getUid(); if(uid==null){startActivity(new Intent(this,LoginActivity.class));finish();return;}
        searchEt=findViewById(R.id.searchMobileEt); RecyclerView rv=findViewById(R.id.chatRecycler); rv.setLayoutManager(new LinearLayoutManager(this)); adapter=new ChatListAdapter(this::openChat); rv.setAdapter(adapter);
        findViewById(R.id.searchBtn).setOnClickListener(v->searchAndStart()); findViewById(R.id.logoutBtn).setOnClickListener(v->{PresenceManager.setOnline(false); auth.signOut(); startActivity(new Intent(this,LoginActivity.class)); finish();}); listenChats();}
    void listenChats(){ chatListener=db.collection("chats").whereArrayContains("members",uid).addSnapshotListener((sn,e)->{ if(e!=null||sn==null)return; List<ChatRow> list=new ArrayList<>(); for(DocumentSnapshot d:sn.getDocuments()){ ChatRow r=new ChatRow(); r.chatId=d.getId(); r.lastMessage=d.getString("lastMessage"); r.time=d.getTimestamp("lastMessageAt"); List<String> members=(List<String>)d.get("members"); if(members==null)continue; for(String m:members) if(!m.equals(uid)) r.otherUid=m; if(r.otherUid==null) continue; list.add(r);} loadUsers(list); }); }
    void loadUsers(List<ChatRow> rows){ if(rows.isEmpty()){adapter.setRows(rows);return;} final int[] left={rows.size()}; for(ChatRow r:rows){ db.collection("users").document(r.otherUid).get().addOnCompleteListener(t->{ if(t.isSuccessful()&&t.getResult()!=null){r.name=t.getResult().getString("name"); r.mobile=t.getResult().getString("mobile");} if(--left[0]==0){ rows.sort((a,b)->{ long ta=a.time==null?0:a.time.toDate().getTime(); long tb=b.time==null?0:b.time.toDate().getTime(); return Long.compare(tb,ta);}); adapter.setRows(rows);} }); } }
    void searchAndStart(){ String mobile=Utils.normalizeMobile(searchEt.getText().toString()); if(!Utils.isValidIndianMobile(mobile)){toast("Valid mobile number likho");return;} db.collection("mobileNumbers").document(mobile).get().addOnSuccessListener(s->{ if(!s.exists()){toast("No Zop Chat user found");return;} String other=s.getString("uid"); if(uid.equals(other)){toast("Ye aapka hi number hai");return;} String chatId=Utils.deterministicChatId(uid,other); Map<String,Object> data=new HashMap<>(); data.put("members",Arrays.asList(uid,other)); Map<String,Object> mm=new HashMap<>(); mm.put(uid,true); mm.put(other,true); data.put("memberMap",mm); data.put("updatedAt",FieldValue.serverTimestamp()); data.put("createdAt",FieldValue.serverTimestamp()); db.collection("chats").document(chatId).set(data,SetOptions.merge()).addOnSuccessListener(x->{ db.collection("users").document(other).get().addOnSuccessListener(u->{ Intent in=new Intent(this,ChatActivity.class); in.putExtra("chatId",chatId); in.putExtra("otherUid",other); in.putExtra("name",u.getString("name")); in.putExtra("mobile",u.getString("mobile")); startActivity(in);});}); }); }
    void openChat(ChatRow r){Intent in=new Intent(this,ChatActivity.class); in.putExtra("chatId",r.chatId); in.putExtra("otherUid",r.otherUid); in.putExtra("name",r.name); in.putExtra("mobile",r.mobile); startActivity(in);} @Override protected void onResume(){super.onResume();PresenceManager.setOnline(true);} @Override protected void onPause(){super.onPause();PresenceManager.setOnline(false);} @Override protected void onDestroy(){if(chatListener!=null)chatListener.remove();super.onDestroy();} void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}
